MINOR_CHOICES = (
('Art History', 'Art History'),
('Asian Studies', 'Asian Studies'),
('Communication', 'Communication'),
('Creative Writing', 'Creative Writing'),
('Dance', 'Dance'),
('Drama/Dance', 'Drama/Dance'),
('History', 'History'),
('Literature', 'Literature'),
('Medical and Scientific Humanities', 'Medical and Scientific Humanities'),
('Music', 'Music'),
('Performing Arts', 'Performing Arts'),
('Philosophy', 'Philosophy'),
('Spanish and Hispanic Area Studies', 'Spanish and Hispanic Area Studies'),
('Visual Arts', 'Visual Arts'),
('Child Development', 'Child Development'),
('Cognitive Science', 'Cognitive Science'),
('Neuroscience', 'Neuroscience'),
('Psychology', 'Psychology'),
('Speech Language Pathology and Audiology', 'Speech Language Pathology and Audiology'),
('Computer Science', 'Computer Science'),
('Information Assurance', 'Information Assurance'),
('Software Engineering', 'Software Engineering'),
('Nanoscience and Technology', 'Nanoscience and Technology'),
('Criminology', 'Criminology'),
('Economics', 'Economics'),
('Geography', 'Geography'),
('Geospatial Information Sciences', 'Geospatial Information Sciences'),
('International Political Economy', 'International Political Economy'),
('Political Science', 'Political Science'),
('Public Affairs', 'Public Affairs'),
('Public Health', 'Public Health'),
('Sociology', 'Sociology'),
('American Studies', 'American Studies'),
('Environmental Studies', 'Environmental Studies'),
('Exercise Studies', 'Exercise Studies'),
('Gender Studies', 'Gender Studies'),
('Healthcare Studies', 'Healthcare Studies'),
('Accounting', 'Accounting'),
('Business Administration', 'Business Administration'),
('Business Intelligence and Analytics', 'Business Intelligence and Analytics'),
('Energy Management', 'Energy Management'),
('Finance', 'Finance'),
('Information Technology and Systems', 'Information Technology and Systems'),
('Innovation and Entrepreneurship', 'Innovation and Entrepreneurship'),
('Insurance', 'Insurance'),
('Marketing', 'Marketing'),
('Organizational Behavior/Human Resources Management', 'Organizational Behavior/Human Resources Management'),
('Actuarial Science', 'Actuarial Science'),
('Biology', 'Biology'),
('Biomolecular Structure', 'Biomolecular Structure'),
('Chemistry', 'Chemistry'),
('Geosciences', 'Geosciences'),
('Mathematics', 'Mathematics'),
('Microbiology', 'Microbiology'),
('Molecular and Cell Biology', 'Molecular and Cell Biology'),
('Neurobiology', 'Neurobiology'),
('Physics', 'Physics'),
('Statistics', 'Statistics'),
)
