MAJOR_CHOICES = (
('ACCOUNTING', 'Accounting'),
('ACTUARIAL_SCIENCE', 'Actuarial Science'),
('AMERICAN_STUDIES', 'American Studies'),
('APPLIED_COGNITION_AND_NEUROSCIENCE', 'Applied Cognition and Neuroscience'),
('APPLIED_SOCIOLOGY', 'Applied Sociology'),
('ART_AND_PERFORMANCE', 'Art and Performance'),
('ARTS_AND_TECHNOLOGY', 'Arts and Technology'),
('AUDIOLOGY', 'Audiology'),
('BIOCHEMISTRY', 'Biochemistry'),
('BIOINFORMATICS_AND_COMPUTATIONAL_BIOLOGY', 'Bioinformatics and Computational Biology'),
('BIOLOGY', 'Biology'),
('BIOMEDICAL_ENGINEERING', 'Biomedical Engineering'),
('BIOTECHNOLOGY', 'Biotechnology'),
('BUSINESS_ADMINISTRATION', 'Business Administration'),
('BUSINESS_ANALYTICS', 'Business Analytics'),
('CELL_AND_MOLECULAR_BIOLOGY', 'Cell and Molecular Biology'),
('CHEMISTRY', 'Chemistry'),
('CHILD_LEARNING_AND_DEVELOPMENT', 'Child Learning and Development'),
('COGNITION_AND_NEUROSCIENCE', 'Cognition and Neuroscience'),
('COGNITIVE_SCIENCE', 'Cognitive Science'),
('COMMUNICATION_DISORDERS', 'Communication Disorders'),
('COMMUNICATION_SCIENCES_AND_DISORDERS', 'Communication Sciences and Disorders'),
('COMPUTER_ENGINEERING', 'Computer Engineering'),
('COMPUTER_SCIENCE', 'Computer Science'),
('CRIMINOLOGY', 'Criminology'),
('ECONOMICS', 'Economics'),
('ELECTRICAL_ENGINEERING', 'Electrical Engineering'),
('EMERGING_MEDIA_AND_COMMUNICATION', 'Emerging Media and Communication'),
('ENERGY_MANAGEMENT', 'Energy Management'),
('FINANCE', 'Finance'),
('GEOSCIENCES', 'Geosciences'),
('GEOSPATIAL_INFORMATION_SCIENCES', 'Geospatial Information Sciences'),
('GLOBAL_BUSINESS', 'Global Business'),
('HEALTHCARE_MANAGEMENT', 'Healthcare Management'),
('HEALTHCARE_STUDIES', 'Healthcare Studies'),
('HISTORICAL_STUDIES', 'Historical Studies'),
('HISTORY', 'History'),
('HUMAN_DEVELOPMENT_AND_EARLY_CHILDHOOD_DISORDERS', 'Human Development and Early Childhood Disorders'),
('HUMANITIES', 'Humanities'),
('HUMANITIES__AESTHETIC_STUDIES', 'Humanities - Aesthetic Studies'),
('HUMANITIES__HISTORY_OF_IDEAS', 'Humanities - History of Ideas'),
('HUMANITIES__STUDIES_IN_LITERATURE', 'Humanities - Studies in Literature'),
('INFORMATION_TECHNOLOGY_AND_MANAGEMENT', 'Information Technology and Management'),
('INFORMATION_TECHNOLOGY_AND_SYSTEMS', 'Information Technology and Systems'),
('INNOVATION_AND_ENTREPRENEURSHIP', 'Innovation and Entrepreneurship'),
('INTERDISCIPLINARY_STUDIES', 'Interdisciplinary Studies'),
('INTERNATIONAL_MANAGEMENT_STUDIES', 'International Management Studies'),
('INTERNATIONAL_POLITICAL_ECONOMY', 'International Political Economy'),
('JUSTICE_ADMINISTRATION_AND_LEADERSHIP', 'Justice Administration and Leadership'),
('LATIN_AMERICAN_STUDIES', 'Latin American Studies'),
('LITERARY_STUDIES', 'Literary Studies'),
('MANAGEMENT_AND_ADMINISTRATIVE_SCIENCES', 'Management and Administrative Sciences'),
('MANAGEMENT_SCIENCE', 'Management Science'),
('MARKETING', 'Marketing'),
('MASTER_OF_BUSINESS_ADMINISTRATION', 'Master of Business Administration'),
('MATERIALS_SCIENCE_AND_ENGINEERING', 'Materials Science and Engineering'),
('MATHEMATICS', 'Mathematics'),
('MATHEMATICS_EDUCATION', 'Mathematics Education'),
('MECHANICAL_ENGINEERING', 'Mechanical Engineering'),
('MOLECULAR_BIOLOGY', 'Molecular Biology'),
('NEUROSCIENCE', 'Neuroscience'),
('PHYSICS', 'Physics'),
('POLITICAL_SCIENCE', 'Political Science'),
('POLITICAL_SCIENCE__CONSTITUTIONAL_LAW_STUDIES', 'Political Science - Constitutional Law Studies'),
('POLITICAL_SCIENCE__LEGISLATIVE_STUDIES', 'Political Science - Legislative Studies'),
('PSYCHOLOGICAL_SCIENCES', 'Psychological Sciences'),
('PSYCHOLOGY', 'Psychology'),
('PUBLIC_AFFAIRS', 'Public Affairs'),
('PUBLIC_POLICY', 'Public Policy'),
('PUBLIC_POLICY_AND_POLITICAL_ECONOMY', 'Public Policy and Political Economy'),
('SCIENCE_EDUCATION', 'Science Education'),
('SOCIOLOGY', 'Sociology'),
('SOFTWARE_ENGINEERING', 'Software Engineering'),
('SPEECHLANGUAGE_PATHOLOGY_AND_AUDIOLOGY', 'Speech-Language Pathology and Audiology'),
('SUPPLY_CHAIN_MANAGEMENT', 'Supply Chain Management'),
('SYSTEMS_ENGINEERING_AND_MANAGEMENT__ECS', 'Systems Engineering and Management * (ECS)'),
('SYSTEMS_ENGINEERING_AND_MANAGEMENT__JSOM', 'Systems Engineering and Management * (JSOM)'),
('TELECOMMUNICATIONS_ENGINEERING', 'Telecommunications Engineering'),
)